### ISSUE TITLE
可以结合jQuery-File-Upload实现上传

### ISSUE THREAD

**Issue by woytu** [helloxz/zdir#10]
https://www.moerats.com/archives/754/

**Comment by helloxz** [comment]
感谢分享，zdir的初衷并不是为了做一个网盘，可能暂时不会考虑上传功能。

**Comment by ExDragine** [comment]
希望能够整合jQuery-File-Upload

> 某些情况下,我们希望用户可以自己上传文档到服务器来进行共享,比如说一个团队服务器,每个人都可以下载和上传所需的文件,而不是单单下载.

希望能接受我们的意见,这也是很多人的期望.

**Comment by helloxz** [comment]
您好，v1.0版本开始已支持文件上传功能，建议尽快更新。
