### ISSUE TITLE
文件全选功能有bug

### ISSUE THREAD

**Issue by modcscom** [helloxz/zdir#102]
文件一个个选择能进行操作，但是全选后不能操作，不能删除等等

**Comment by mengtaixiao** [comment]
我看了，全选他把那个返回上级的按钮也选中了，那个返回上级的按钮不是文件，所以没法下载
全选，然后把返回上级的按钮 的勾去掉，就可以下载了


> 文件一个个选择能进行操作，但是全选后不能操作，不能删除等等

**Comment by helloxz** [comment]
> 我看了，全选他把那个返回上级的按钮也选中了，那个返回上级的按钮不是文件，所以没法下载 全选，然后把返回上级的按钮 的勾去掉，就可以下载了
> 
> > 文件一个个选择能进行操作，但是全选后不能操作，不能删除等等

正解，这个是已知问题，后面会想办法修复。
