### ISSUE TITLE
希望增加排序功能

### ISSUE THREAD

**Issue by zmrblog** [helloxz/zdir#11]
如根据文件大小、文件名、修改时间等排序

**Comment by SlovEnt** [comment]
同建议，最好能先排序文件夹再排序文件。感激老师的努力。

**Comment by helloxz** [comment]
> 同建议，最好能先排序文件夹再排序文件。感激老师的努力。
@SlovEnt v1.1已推送，已支持`文件夹与文件重新排序（默认文件夹在最前面）`，建议尽快更新。

**Comment by SlovEnt** [comment]
> > 同建议，最好能先排序文件夹再排序文件。感激老师的努力。
> 
> @SlovEnt v1.1已推送，已支持`文件夹与文件重新排序（默认文件夹在最前面）`，建议尽快更新。

请问老师，能否在文件修改时间处增加个热点，点击标题后可以按文件更新时间进行排序。

**Comment by helloxz** [comment]
@zmrblog @SlovEnt 最新的3.0重构版本已经支持按大小、按文件类型、按修改时间来进行排序，欢迎安装体验。
