### ISSUE TITLE
部署在网站的二级目录下时，复制文件链接会出错

### ISSUE THREAD

**Issue by WenPeiyu** [helloxz/zdir#16]
例如部署在a.com/zdir下，但复制文件链接的地址仍在a.com/下，这应该是个bug。

**Comment by johnpoint** [comment]
应该是还没有支持吧，我看见README那儿写着放在根目录那

**Comment by WenPeiyu** [comment]
> > 例如部署在a.com/zdir下，但复制文件链接的地址仍在a.com/下，这应该是个bug。
> 
> 嘤嘤嘤，已经解决了
> [详情看这里](https://github.com/helloxz/zdir/commit/89ff9202d94fd0dcd1f6e56dc8570a351c4408da)

多谢啦~

**Comment by helloxz** [comment]
这个问题已经修复，使用最新的`static/embed.js` 覆盖即可。
