### ISSUE TITLE
希望可以增加readme文件直接显示

### ISSUE THREAD

**Issue by rumosky** [helloxz/zdir#18]
就是在文件夹下面放一个readme，在目录之后直接显示那个md文件或者HTML文件，有一个魔改的可以参考一下，我试过，这个魔改的中文命名没有问题，稳定运行四个多月都没事。
希望可以融合魔改的那个程序的底部显示readme，中文目录显示。
https://github.com/ToyoDAdoubi/DirectoryLister

**Comment by baoang** [comment]
https://github.com/Akyuu/DirectoryLister

DirectoryLister中文有问题是较早前的事了，后来它更新过，但仍有一些问题，在挖站否有个介绍Zdir的文章后有说明。逗比的修改版的确能够解决中文显示问题，不过不知道是什么原因。

上面这个链接是另一个fork的作品，也没有问题。

**Comment by andyhuai** [comment]
同样希望能够直接显示reame内容，这样很简洁

**Comment by helloxz** [comment]
您好，v1.3版本已增加README.md直接显示在顶部，感谢支持。同时Zdir v1.3也解决了中文显示问题，感谢支持。
