### ISSUE TITLE
限制IP的功能好像失效了。。。

### ISSUE THREAD

**Issue by CYF--cc** [helloxz/zdir#22]

**Comment by CYF--cc** [comment]
原来是这样……我还以为是限制登录呢
现在的后台管理也是一样的吗

**Comment by baoang** [comment]
> 
> 
> 原来是这样……我还以为是限制登录呢
> 现在的后台管理也是一样的吗

“后台管理”？
这个真没见过，我读到过以前的一些介绍文章，说`function/admin.php`可以进后台管理，不过我现在用的是1.0正式版，目录下已经没有这个东西了。
我估计你所说的后台管理就是指的 &admin，或者?admin吧。

**Comment by helloxz** [comment]
这是最新版的帮助文档：[https://doc.xiaoz.me/#/zdir/maintain](https://doc.xiaoz.me/#/zdir/maintain) ，最新版支持文件管理。
