### ISSUE TITLE
有几个问题提醒下

### ISSUE THREAD

**Issue by simayubo** [helloxz/zdir#26]
- 屏蔽目录，请检测子目录，现在子目录通过输入网址还可以访问
- 建议隐藏所有php后缀的文件
- 请屏蔽所有PHP文件的直接访问：建议在index.php中定义一个常量，在不需要直接访问的php文件中判断是否已经定义常量，没有定义则返回错误

**Comment by helloxz** [comment]
感谢您的建议，下个版本进行改进。
