### ISSUE TITLE
文件太多，只能出现：文件索引 - 该数据缓存于2019-04-02 03:14:42，没有内容。

### ISSUE THREAD

**Issue by ivannovs** [helloxz/zdir#29]
文件太多，只能出现：文件索引 - 该数据缓存于2019-04-02 03:14:42，没有内容。请老板看一下。

**Comment by helloxz** [comment]
1. 检查`functions/caches`目录是否可读可写
2. 尝试在`functions/indexes.php`顶部加入一行代码`ini_set('max_execution_time', '0');` 再试下是否正常
3. 如果问题解决了，请回复消息并关闭Issues，感谢

**Comment by ivannovs** [comment]
改了，还是不行，还是报同样错。
[root@host /var/www/html/functions/caches]$ l
total 8
-rwxrwxrwx 1 root   root      0 Mar 26 18:14 index.html
drwxrwxrwx 2 root   root   4096 Apr  2 11:56 .
drwxr-xr-x 3 root   root   4096 Apr  4 10:59 ..
-rwxrwxrwx 1 apache apache    0 Apr  4 10:59 indexes.html

执行完，结果文件大小还是0

**Comment by helloxz** [comment]
先把`functions/caches/indexes.html` 这个文件删除，然后再重新执行一次。

**Comment by ivannovs** [comment]
还是一样，出不来，是不是在别处还有关于超时的控制。

**Comment by helloxz** [comment]
在`index.php`最前面再加一行`ini_set('max_execution_time', '0');`，然后删除`functions/caches/indexes.html`再重新生成试试。

**Comment by ivannovs** [comment]
大体看出原因了，我把         echo $url;    这句放开，发现URL是http打头，我的网址是https打头加了ssl协议。
可是怎么改呢?我直接写死试试。

**Comment by ivannovs** [comment]
$url = "https://*****"   开始转了。。。。。。应该是找到原因所在了，老板看看怎么取URL前缀，要能识别出https协议。

**Comment by ivannovs** [comment]
问题写决了，我看下现get_url的在非80 443端口上是http...解决了，谢谢！
