### ISSUE TITLE
文件名太长无法显示

### ISSUE THREAD

**Issue by bingotl** [helloxz/zdir#3]
http://wx2.sinaimg.cn/mw690/0060lm7Tly1fskw55dczij30gj0ftmx7.jpg

**Comment by helloxz** [comment]
* 是不是目录名有中文呀？如果带有中文可能显示有问题。
* 如果不带中文，请提供下目录名我这边测试一下。

**Comment by bingotl** [comment]
是中文的，中文全无法显示，求修复额....

**Comment by helloxz** [comment]
最新版中文已经解决（Linux下测试）
