### ISSUE TITLE
新建目录默认不显示，需要点击.. 才显示呢。

### ISSUE THREAD

**Issue by piaoyun** [helloxz/zdir#34]
新建目录默认不显示，需要点击.. 才显示呢。

访问首页。默认不出来目录。
查看了config.php  目录也没有做排除呢

目录名称：soft 或者softs  通过FTP新建。或者登陆后台，新建都是默认不显示

点击文件列表顶部的..

后，可以看到目录
![QQ截图20190704104628](https://user-images.githubusercontent.com/3724475/60636431-07ab9f80-9e49-11e9-9b82-435e1f830092.png)
![QQ截图20190704104639](https://user-images.githubusercontent.com/3724475/60636432-07ab9f80-9e49-11e9-80d5-5a7290be821b.png)

**Comment by helloxz** [comment]
这个BUG已经修复，请下载最新版覆盖即可。
