### ISSUE TITLE
不能够指定列目录的文件夹吗

### ISSUE THREAD

**Issue by yesmiley** [helloxz/zdir#36]
和程序混在一起太乱了。。。希望可以指定一个存储目录 比如 storage 这样的然后统一收纳

**Comment by xmapst** [comment]
上传目录可以修改admin.php里的document_root参数即可，但是前面展示的还没找到解决方法

**Comment by xmapst** [comment]
指定存放目录，修改好了；
在网站根目录创建一个命名为upload的文件夹；
修改如下
```
config.php +末尾加上
//设置上传目录,以网站根目录开始
$uploadDir = "/upload"

home.php +第四行，第196行修改
//$thedir = __DIR__;
$thedir = $_SERVER['DOCUMENT_ROOT'].$uploadDir;

//$url = “.”.$dir.'/'.$showdir; 
$url = $uploadDir.$dir.'/'.$showdir; 

admin.php +第49行
//$root_path = $_SERVER['DOCUMENT_ROOT'];
$root_path = $_SERVER['DOCUMENT_ROOT'].$uploadDir;
```
修改这几处即可，其他细处暂未检查

**Comment by Googleing** [comment]
@xmapst 谢谢您的帮助，不过这边发现还是有点问题，主要是文件无法正确打开，Nginx 报错 404。应该还有地方没改到。

**Comment by tryboy1978** [comment]
> @xmapst 谢谢您的帮助，不过这边发现还是有点问题，主要是文件无法正确打开，Nginx 报错 404。应该还有地方没改到。

我按@xmapst 的修改，没发现打不开的问题哟。

**Comment by yesmiley** [comment]
> > @xmapst 谢谢您的帮助，不过这边发现还是有点问题，主要是文件无法正确打开，Nginx 报错 404。应该还有地方没改到。
> 
> 我按@xmapst 的修改，没发现打不开的问题哟。

重新试了下确实可以了，之前可能是哪里改错了。多谢两位

**Comment by wxlost** [comment]
> 指定存放目录，修改好了；
> 在网站根目录创建一个命名为upload的文件夹；
> 修改如下
> 
> ```
> config.php +末尾加上
> //设置上传目录,以网站根目录开始
> $uploadDir = "/upload"
> 
> home.php +第四行，第196行修改
> //$thedir = __DIR__;
> $thedir = $_SERVER['DOCUMENT_ROOT'].$uploadDir;
> 
> //$url = “.”.$dir.'/'.$showdir; 
> $url = $uploadDir.$dir.'/'.$showdir; 
> 
> admin.php +第49行
> //$root_path = $_SERVER['DOCUMENT_ROOT'];
> $root_path = $_SERVER['DOCUMENT_ROOT'].$uploadDir;
> ```
> 
> 修改这几处即可，其他细处暂未检查

home.php +第四行，第196行修改
,现在196是
```
if($showdir == '..'){
```
该如何修改呢
