### ISSUE TITLE
无法识别mkv格式视频

### ISSUE THREAD

**Issue by Rayzggz** [helloxz/zdir#47]
无法识别mkv格式视频
mkv视频被识别成了文件夹

**Comment by Rayzggz** [comment]
不好意思，问题文件名中包含点“.”导致的，同时也希望修复

**Comment by helloxz** [comment]
是`.`开头的文件夹吗？

**Comment by Rayzggz** [comment]
不是，如：

君の膵臓をたべたい.2018.BDrip.1080p.X265.AAC-233.mkv
