### ISSUE TITLE
这个程序非常棒，希望能索引链接

### ISSUE THREAD

**Issue by deepdream88** [helloxz/zdir#49]
我最近在寻找一款 链接目录程序，类似于浏览器收藏夹那种，如果有哪位朋友知道，请给我说一下，谢谢！

**Comment by helloxz** [comment]
没明白您具体需求呢

**Comment by deepdream88** [comment]
> 没明白您具体需求呢

好的，我详细描述一下，您知道永硕E盘么？可以在文件夹中添加文件，还可以添加一个超链接，我最近就在找这种能索引链接的程序，或者一款网页版书签（收藏夹）
