### ISSUE TITLE
README.md预览显示存在错位

### ISSUE THREAD

**Issue by wxlost** [helloxz/zdir#50]
README.md预览显示存在错位.

![QQ图片20200323091306](https://user-images.githubusercontent.com/19698455/77270373-b8631300-6ce6-11ea-8efd-650472f3a2fd.png)
![QQ图片20200323091420](https://user-images.githubusercontent.com/19698455/77270376-ba2cd680-6ce6-11ea-88aa-786bf6450e1f.png)

**Comment by helloxz** [comment]
您好，麻烦告知下所使用的浏览器和版本号，以及屏幕的分辨率，谢谢。

**Comment by wxlost** [comment]
> 您好，麻烦告知下所使用的浏览器和版本号，以及屏幕的分辨率，谢谢。
```
版本 4.1.7.182（正式版本） （64 位） (Chromium 78.0.3904.108)
IE11
1440*900
```
