### ISSUE TITLE
请教预览下载分离

### ISSUE THREAD

**Issue by wxlost** [helloxz/zdir#60]
作者你好.感谢分享如此好的作品

目前个人需求是:
访问 a.bb.com 预览网盘内容
然后点击下载的 实际地址是 b.bb.com:1234
不知该修改那个文件的内容会形成此效果

**Comment by wxlost** [comment]
唉

**Comment by mengtaixiao** [comment]
你这魔改的挺好看的，功能也直接，图片预览放上去就行了，下载、看hash也不需要二次点击，可惜不会前端，改不出来

> > > 建议参考下我的方法，用浏览器F12应该就能看懂。 https://f.hiwhf.cn/?dir=/%E6%B5%8B%E8%AF%95%E7%9B%AE%E5%BD%95
> > 
> > 
> > emmm F12调试看了半天没看懂。。。求答疑
> 
> 你看下那个diy.js 和请求的file.json 请求的那个hasfile.php的内容如图 ![vefdsv.png](https://camo.githubusercontent.com/1d14e20939b4118c8aec85114660b5f80bcb17d2ac80d35ac4655a75e4f402e6/68747470733a2f2f692e6c6f6c692e6e65742f323032312f31302f32362f39546934657451736a3536625270312e706e67)

**Comment by helloxz** [comment]
> 你这魔改的挺好看的，功能也直接，图片预览放上去就行了，下载、看hash也不需要二次点击，可惜不会前端，改不出来
> 
> > > > 建议参考下我的方法，用浏览器F12应该就能看懂。 https://f.hiwhf.cn/?dir=/%E6%B5%8B%E8%AF%95%E7%9B%AE%E5%BD%95
> > > 
> > > 
> > > emmm F12调试看了半天没看懂。。。求答疑
> > 
> > 
> > 你看下那个diy.js 和请求的file.json 请求的那个hasfile.php的内容如图 ![vefdsv.png](https://camo.githubusercontent.com/1d14e20939b4118c8aec85114660b5f80bcb17d2ac80d35ac4655a75e4f402e6/68747470733a2f2f692e6c6f6c692e6e65742f323032312f31302f32362f39546934657451736a3536625270312e706e67)

他这个是早期的`1.x/2.x`版本，使用PHP开发，已经停止更新了。现在重心在`3.x`版本，使用Golang重构。
