### ISSUE TITLE
文件管理器显示问题

### ISSUE THREAD

**Issue by sino1641** [helloxz/zdir#66]
感谢作者，初次使用，UI很好看
反馈文件管理器两处显示问题
1. 执行操作栏图标不显示
    ![image](https://user-images.githubusercontent.com/13870295/133150785-ff91813d-c410-43aa-a74c-9802bf2ecb31.png)
2. 上传窗口没有上传按钮
    ![image](https://user-images.githubusercontent.com/13870295/133150941-372e207f-80cb-487a-9f8f-0081d6cabd0f.png)

**Comment by helloxz** [comment]
这个应该是网络原因导致部分静态资源加载失败了，你是移动网络吗？后续我考虑下看能否替换文件管理的CDN静态资源。

**Comment by sino1641** [comment]
> 这个应该是网络原因导致部分静态资源加载失败了，你是移动网络吗？后续我考虑下看能否替换文件管理的CDN静态资源。

是的 但是这边通过内网访问也是同样的显示，请问也是cdn的问题吗？

**Comment by helloxz** [comment]
`PHP`版本已经不再维护，推荐使用更加强大的`3.x`版本：[https://doc.xiaoz.me/books/zdir-3](https://doc.xiaoz.me/books/zdir-3)
