### ISSUE TITLE
建议 qrcode 二维码生成本地化

### ISSUE THREAD

**Issue by hackxiu** [helloxz/zdir#67]
建议 qrcode 二维码生成本地化，完全可以用JS实现

引入 https://github.com/KeeeX/qrcodejs 

这个JS 就实现了，或者其他 JS 本地化 二维码生成，依赖网络生成二维码总是失效，不可取。。

**Comment by WHFo** [comment]
> 建议 qrcode 二维码生成本地化，完全可以用JS实现
> 
> 引入 https://github.com/KeeeX/qrcodejs
> 
> 这个JS 就实现了，或者其他 JS 本地化 二维码生成，依赖网络生成二维码总是失效，不可取。。

#68 我的pr已经合并进代码中了，您可以试下。

**Comment by helloxz** [comment]
Zdir 3.0已经重构完成，所有资源全部本地化。可以安装试试。
