### ISSUE TITLE
windows 下用 upupw 环境 PHP 不管用5.6还是 7.2 还是7.4

### ISSUE THREAD

**Issue by nobita215** [helloxz/zdir#72]
![image](https://user-images.githubusercontent.com/12522734/153965031-d087f35f-f207-46b6-ad5b-0795fe0e5276.png)
后台管理中文目录都是乱码，前台没问题。

**Comment by helloxz** [comment]
`3.x`版本已经使用golang重构，理论上不会再出现中文乱码，建议使用`3.x`版本。
