### ISSUE TITLE
在手机浏览器上点开视频文件后，没有关闭视频播放器的按钮，只能用浏览器的返回上一页功能返回上一页，能增加一个关闭播放器的按钮吗？

### ISSUE THREAD

**Issue by nobita215** [helloxz/zdir#73]
在手机浏览器上点开视频文件后，没有关闭视频播放器的按钮，只能用浏览器的返回上一页功能返回上一页，能增加一个关闭播放器的按钮吗？电脑浏览器访问是有关闭按钮的。
![origin_img_v2_c46f0cca-0133-41d7-b204-630b8caf985g](https://user-images.githubusercontent.com/12522734/153968880-14b6a0cc-3510-4df6-8e75-39c9c1c3786e.jpg)

**Comment by helloxz** [comment]
你试试看最新的`3.x`版本呢。
