### ISSUE TITLE
API返回https但前端是http

### ISSUE THREAD

**Issue by hexstr** [helloxz/zdir#80]
如图，图1是chrome控制台看到的请求

![Snipaste_2022-10-26_21-53-39](https://user-images.githubusercontent.com/28940831/198045243-b529383c-fc0e-4881-b986-d004ed19fd31.jpg)

图2是审查元素

![Snipaste_2022-10-26_21-54-07](https://user-images.githubusercontent.com/28940831/198045328-06d0c267-9f6e-447a-9344-4f3f2d3bc594.jpg)

`config.ini`中`public_domain`也填写了`https://`

**Comment by helloxz** [comment]
另外如果配置了nginx的话，可以将末尾的`/public`去掉。public_domain只保留`https://domain.com`即可。
