### ISSUE TITLE
3.0一下子给我整不会用了。

### ISSUE THREAD

**Issue by qzwl** [helloxz/zdir#83]
还是老老实实用2.0吧
顺带问一下，能不能把上架到宝塔面板呢。

**Comment by helloxz** [comment]
3.x提供了Linux一键安装方式：[https://doc.xiaoz.me/books/zdir-3/page/linuxzdir](https://doc.xiaoz.me/books/zdir-3/page/linuxzdir) 不依赖PHP环境，只需要服务器满足条件即可。

暂时没有上架宝塔面板的计划，感谢支持。
