### ISSUE TITLE
一个小缺陷

### ISSUE THREAD

**Issue by BlueAndStar** [helloxz/zdir#85]
在设置`config.ini` 中的站点名称之后，还需要修改`index.html`中的`title`值，否则每次页面刷新浏览器标题栏都会先出现`Zdir`，然后再跳转到设定的站点名称。
![image](https://user-images.githubusercontent.com/105478325/206628187-986a2918-305f-4832-b0b3-484da81bf1d9.png)

**Comment by helloxz** [comment]
这个是因为前端使用的Vue单页面应用，所以会出现这个预期内的问题，暂时没有更好的解决方案，单页面应用都存在此问题。
