### ISSUE TITLE
测试了几个文件管理器，zdir文件数多时，文件夹基本打不开

### ISSUE THREAD

**Issue by modcscom** [helloxz/zdir#87]
同一个文件夹，里面有近300个mp4文件，其他文件管理器基本瞬间打开了，zdir一直在转圈圈打不开。

**Comment by helloxz** [comment]
性能不应该这么弱，可能触发了什么BUG，有相关的地址吗？

**Comment by modcscom** [comment]
http://152.70.238.96:6080/#/html 
http://152.70.238.96:5238/local/html
对比看下

**Comment by helloxz** [comment]
感谢您的反馈，两个地址我都试了下，Zdir后端接口耗费`400ms`左右（不到1s），后端方面性能上没问题。我这边整体打开都很快，但Zdir整体速度确实不如PanIndex，且在手机上存在略微卡顿。Zdir前端性可能存在一些性能问题，后续我会进行优化。

**Comment by helloxz** [comment]
`3.2.0`版本已经发布，新增了文件列表分页支持，实测单个目录下1万个文件，已经毫无压力，推荐更新试试。

**Comment by helloxz** [comment]
老板，空了可以更新试一下哦。
