### ISSUE TITLE
文档预览功能建议用syntaxhighlighter

### ISSUE THREAD

**Issue by nobiyou** [helloxz/zdir#9]
我发现挺好的，就改了下，用syntaxhighlighter来预览代码，真的很好看的，只要写文件的判断即可，现有用的这个界面等都不能与syntaxhighlighter相比，建议用上。

**Comment by helloxz** [comment]
谢谢，我去看下syntaxhighlighter

**Comment by helloxz** [comment]
最新的3.0.0重构版本使用了`codemirror`来预览代码，可以安装试试效果咋样。
